#!/bin/bash

if ! command -v jq > /dev/null; then
  cat <<JQ
jq command not found. Install with:
  brew install jq
JQ
  exit 1
fi

action=${1:-help}
arg=$2

help() {
   cat <<HELP
Usage: post-commit-hooks [action]
Actions:
  help                    show this help message
  install                 compile and copy the postcommit hook to dev-services and setup the hook on each bucket
  add                     add the postcommit hook to all riak buckets
  remove                  remove the postcommit hook from all riak buckets
  buckets                 list all of the riak buckets
  list                    list all riak buckets and their postcommit hook setup
HELP
}

install() {
  make
  make install
  add
  echo "Now run: 'services restart' to install the postcommit hook into your development Riak."
}

buckets() {
  curl -s 127.0.0.1:9150/riak\?buckets\=true | jq -r ".buckets[]" | sort
}

add() {
  update_buckets '{"props":{"postcommit":[{"mod":"postcommit_hook","fun":"send_to_kafka_riak_commitlog"}]}}'
}

remove() {
  update_buckets '{"props":{"postcommit":[]}}'
}

list() {
  buckets | while read _bucket; do
    echo -n "$_bucket^"
    _bucket=`echo $_bucket | sed -e 's/\//%2F/'`
    curl -s 127.0.0.1:9150/buckets/$_bucket/props | jq -c .props.postcommit
  done | column -s "^" -t
}

update_buckets() {
  _data=$1
  buckets | while read _bucket; do
    _bucket=`echo $_bucket | sed -e 's/\//%2F/'`
    curl -s 127.0.0.1:9150/buckets/$_bucket/props \
      -XPUT \
      -H "Content-Type: application/json" \
      -d $_data
  done
}

$action $arg
